In [1]:
pip install transformers

In [2]:
from transformers import pipeline
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Device set to use cuda:0


In [4]:
classifier("Hello i love the product you are selling")

[{'label': 'POSITIVE', 'score': 0.999854564666748}]

In [5]:
classifier("Hello i hate the product you are selling")

[{'label': 'NEGATIVE', 'score': 0.9990851879119873}]

In [7]:
classifier("The laptop is too slow and rubbish. It has no features but you can buy it")

[{'label': 'NEGATIVE', 'score': 0.9983702301979065}]

In [9]:
result=classifier(["The work life is so good","I hope you should die ASAP"])
for results in result:
  print(f"label:{results['label']},with score:{round(results['score'],4)}")

label:POSITIVE,with score:0.9999
label:NEGATIVE,with score:0.9967


In [11]:
translation=pipeline("translation",model="google-t5/t5-base")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/pipelines/__init__.py:1156: UserWarning: "translation" task was used, instead of "translation_XX_to_YY", defaulting to "translation_en_to_de"
  warnings.warn(
Device set to use cuda:0


In [16]:
translation("translate English to Spanish:hello and welcome to my home")

[{'translation_text': 'Spanisch:Hallo und willkommen zu meiner Heimat'}]

In [17]:
translation("translate English to French:hello and welcome to my home")

[{'translation_text': 'Bonjour et bienvenue à ma maison'}]

In [19]:
translator = pipeline("translation_en_to_fr", model="Helsinki-NLP/opus-mt-en-fr")
translation = translator("Hello and welcome to my home", max_length=50)
print("French Translation:", translation[0]['translation_text'])


Device set to use cuda:0


French Translation: Bonjour et bienvenue chez moi


In [25]:
from transformers import pipeline

hindi_translator = pipeline("translation_en_to_hi", model="Helsinki-NLP/opus-mt-en-hi")
text = "Her eyes are so beautiful"
translation = hindi_translator(text, max_length=50)

print("Hindi Translation:", translation[0]['translation_text'])


Device set to use cuda:0


Hindi Translation: उसकी आँखें बहुत सुंदर हैं


In [28]:
# to load the model the tokenizer are must to be called()
from transformers import AutoTokenizer,TFAutoModelForSequenceClassification

In [32]:
model_name="nlptown/bert-base-multilingual-uncased-sentiment"
# This model only exist in PyTorch, so we use the 'from_pt' flag to import that model in Tensorflow.
model=TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer=AutoTokenizer.from_pretrained(model_name)
classifier=pipeline("sentiment-analysis",model=model,tokenizer=tokenizer)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.
Device set to use 0


In [33]:
classifier("I like the way he speaks")

[{'label': '4 stars', 'score': 0.5556120276451111}]

In [35]:
from transformers import AutoTokenizer,TFAutoModelForSequenceClassification

In [37]:
model_name="nlptown/bert-base-multilingual-uncased-sentiment"
tf_model=TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer=AutoTokenizer.from_pretrained(model_name)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [38]:
inputs=tokenizer("We are very happy to show you the best code")

In [39]:
print(inputs)

{'input_ids': [101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103, 11146, 13121, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [40]:
tf_batch=tokenizer(
    ['We are very happy to show you the best code','I like the way they drive'],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors='tf'

)

In [41]:
tf_batch

{'input_ids': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[  101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103,
        11146, 13121,   102],
       [  101,   151, 11531, 10103, 12140, 10578, 15834,   102,     0,
            0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]], dtype=int32)>}

In [45]:
for key,value in tf_batch.items():
  print(f"{key}:{value.numpy().tolist()}")

input_ids:[[101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103, 11146, 13121, 102], [101, 151, 11531, 10103, 12140, 10578, 15834, 102, 0, 0, 0, 0]]
token_type_ids:[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
attention_mask:[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]]
